wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: huggingface
    huggingface_version: 4.8.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.10
    t:
      1:
      - 1
      - 3
      - 5
      - 9
      - 11
      4: 3.7.10
      5: 0.11.2
      6: 4.8.2
      8:
      - 1
      - 2
      - 5
